restroom_rater/urls.py
from django.urls import path
from . import views, views_venues
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', views.homepage, name='homepage'),

    # Venue
    path('venues/list/', views_venues.venue_list, name='venue_list'),
    path('venues/detail/<int:venue_pk>/', views_venues.venue_detail, name='venue_detail'),

    # Review
    path('reviews/detail/<int:review_pk>/',views.review_detail, name='review_detail'),

    # Breadcrumbs
    path('breadcrumbs/', views.breadcrumbs, name='breadcrumbs'),

    # Favicon
    # path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico')))
]

restroomrater/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restroom_rater.urls'))
]

restroom_rater/models.py
import datetime
from django.db import models
from django.core.validators import MinValueValidator


class Venue(models.Model):
    name = models.CharField(max_length=200, blank=False)
    category = models.CharField(max_length=200, blank=False)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200, blank=False)
    state = models.CharField(max_length=2, blank=False)    # What about international?
    zip_code = models.CharField(max_length=5, blank=False)
    image = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name} // {self.city}, {self.state} {self.zip_code}'


class RestroomReview(models.Model):
    MEN = 'M'
    WOMEN = 'W'
    UNISEX = 'U'
    FAMILY = 'F'
    RESTROOM_TYPE_CHOICES = [
        ('M', 'Men'),
        ('W', 'Women'),
        ('U', 'Unisex'),
        ('F', 'Family')
    ]
    RATING_CHOICES = [
        (1, 'Poor'),
        (2, 'Average'),
        (3, 'Good'),
        (4, 'Very Good'),
        (5, 'Excellent')
    ]
    venue = models.ForeignKey(Venue, blank=False, on_delete=models.CASCADE)
    user = models.CharField(max_length=20, blank=False)
    public = models.BooleanField(blank=False)
    rest_type = models.CharField(
        max_length=1, 
        choices=RESTROOM_TYPE_CHOICES, 
        default=MEN
    )
    baby = models.BooleanField('Changing Table')
    needle = models.BooleanField('Sharps Container')
    handicap = models.BooleanField('Handicap Accessible')
    rating = models.IntegerField(choices=RATING_CHOICES, default=1)
    title = models.CharField(max_length=100, blank=False)
    comment = models.TextField(max_length=1000, blank=False)
    posted_date = models.DateTimeField(blank=False)

    def publish(self):
        posted_date = datetime.datetime.today()
        self.save()
    
    def __str__(self):
        return f'Review for {self.venue.name} by {self.user}'

restroom_rater/forms.py
from django import forms
from .models import RestroomReview

from django.forms import ValidationError
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


# form to search zip code
class SearchForm(forms.Form):
    zip_code = forms.CharField(required=True, label='Zip Code', max_length=5)


# form to review restroom
class RestroomForm(forms.ModelForm):
    user = forms.CharField(max_length=20, min_length=1, required=True, 
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    title = forms.CharField(max_length=100, min_length=1, required=True, 
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}))
    comment = forms.CharField(max_length=1000, required=True, 
                            widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Leave your review here'}))

    class Meta:
        model = RestroomReview
        fields = (
            'user', 'public', 'rest_type', 
            'baby', 'needle', 'handicap', 
            'rating', 'title', 'comment'
            )

restroom_rater/views.py
from .forms import RestroomForm
from django.utils import timezone
from .models import Venue, RestroomReview
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse


def homepage(request):
    reviews = RestroomReview.objects.all()
    return render(request, 'restroom_rater/homepage.html', {'reviews': reviews})


def review_detail(request, review_pk):
    review = get_object_or_404(RestroomReview, pk=review_pk)
    return render(request, 'restroom_rater/review_detail.html', {'review': review})

def breadcrumbs(request):
    return render(request, 'restroom_rater/breadcrumbs.html')

def dello(request):
    return HttpResponse('This app is deployed on App Engine!!')

restroom_rater/templates/restroom_rater/base.html
{% load static %}
{% load widget_tweaks %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <meta property="og:url" content="https://restroomrater.herokuapp.com">
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Restroom Rater">
        <meta property="og:description" content="Rate & review you favorite restrooms!">
        <meta name="image" property="og:image" content="{% static 'img/restroomRaterCard.png' %}">
        <meta property="og:image:type" content="image/png">

        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:creator" content="@danibarstad">
        <meta name="twitter:title" content="Restroom Rater">
        <meta name="twitter:image:src" content="https://raw.githubusercontent.com/danibarstad/RestroomRater/master/restroom_rater/static/img/restroomRaterCard.png">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
        <link rel="mask-icon" href="{% static 'img/safari-pinned-tab.svg' %}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">

        <title>Restroom Rater</title>
        
    </head>
    
    <body>

        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 class="text-center">RESTROOM RATER</h1>
                </div>
            </div>

            <!-- form to enter zip code -->
            <div class="container">
                <div class="row">
                    <div class="col">
                        <form action="{% url 'venue_list' %}">
                            {% render_field search_form.zip_code.label %}:<br>
                            {% render_field search_form.zip_code class="form-control" style="display: inline;" placeholder="12345" %}
                            <input type='submit' value='SEARCH'>
                        </form>
                    </div>
                </div>
            </div>

            {% block content %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>

    <footer>
        <div class="container">
            <hr class="mt-0 mb-4">
            <div class="venue_list" style="margin: auto; text-align: center;">
                created by <a style="font-weight: bold;" target="_blank" href="https://danibarstad.com">danibarstad</a>
                | <a style="font-weight: bold;" target="_blank" href="https://github.com/danibarstad/RestroomRater">GitHub</a>
            </div>
        </div>
    </footer>
</html>

restroom_rater/templates/restroom_rater/breadcrumbs.html
<!-- NOT IMPLEMENTED -->
<!-- list of breadcrumbs -->

<span id='breadcrumbs'>
    <a href="{% url 'homepage' %}">Home</a>
    / 
    <a href="{% url 'venue_list' %}?zip_code={{ review.venue.zip_code }}">Venue List</a>
    /
    <a href="{% url 'venue_detail' venue_pk=review.venue.pk %}">{{ review.venue.name }}</a>
    /
    <a href="{% url 'review_detail' review_pk=review.pk %}">{{ review.title }}</a>
</span>

restroom_rater/templates/restroom_rater/homepage.html
{% extends 'restroom_rater/base.html' %}
{% block content %}

    <!-- breadcrumbs -->
    <div class="container">
        <div class="row">
            <div class="col">
                <span id='breadcrumbs'>
                    <p><a href="{% url 'homepage' %}">Home</a></p>
                </span>
            </div>
        </div>
    </div>
    <hr class="mt-0 mb-4">

    
    <div class="container">
        <h4>Reviews</h4>
        {% for review in reviews %}
            <div class="venue_list">
                <h4><a href="{% url 'review_detail' review_pk=review.pk %}">{{ review.title }}</a></h4> 
                <p>by {{ review.user }} for <a href="{% url 'venue_detail' venue_pk=review.venue.pk %}">{{ review.venue.name }}</a></p>
                <div class="review_text">
                    <p>{{ review.rating }}\5&emsp;<i>{{ review.comment }}</i></p>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

restroom_rater/templates/restroom_rater/review_detail.html
{% extends 'restroom_rater/base.html' %}
{% block content %}

    <!-- breadcrumbs -->
        <div class="container">
            <div class="row">
                <div class="col">
                    <span id='breadcrumbs'>
                        <a href="{% url 'homepage' %}">Home</a>
                        / 
                        <a href="{% url 'venue_list' %}?zip_code={{ review.venue.zip_code }}">Venue List</a>
                        /
                        <a href="{% url 'venue_detail' venue_pk=review.venue.pk %}">{{ review.venue.name }}</a>
                        /
                        <a href="{% url 'review_detail' review_pk=review.pk %}">{{ review.title }}</a>
                    </span>
                </div>
            </div>
        </div>

    <!-- venue image -->
    <!-- <img class="venue_images" src="{{ review.venue.image }}" alt="{{ review.venue.name }}"> -->

    <!-- review details -->
    <div class="container">
        <div class="row">
            <div class="col">
                <h3><a href="{% url 'venue_detail' venue_pk=review.venue.pk %}">{{ review.venue.name }}</a></h3>
                <div class="venue_list">
                    <h3 style="text-align: center;">{{ review.title }}</h3>
                    <p style="text-align: center;"><span class="review_column">by</span> {{ review.user }}</p>
                    <p><span class="review_column">Public:</span> {{ review.public }}</p>
                    <p><span class="review_column">Type:</span> {{ review.get_rest_type_display }}</p>
                    <p><span class="review_column">Changing Table:</span> {{ review.baby }}</p>
                    <p><span class="review_column">Sharps Container:</span> {{ review.needle }}</p>
                    <p><span class="review_column">Handicap Accessible:</span> {{ review.handicap }}</p>
                    <p><span class="review_column">Rating:</span> {{ review.get_rating_display }}</p>
                    <p><span class="review_column">Comment:</span><br>"<em>{{ review.comment }}</em>"</p>
                    <p><span class="review_column">Reviewed on</span> {{ review.posted_date }}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

restroom_rater/templates/restroom_rater/venue_detail.html
{% extends 'restroom_rater/base.html' %}
{% block content %}
{% load widget_tweaks %}

    <!-- breadcrumbs -->
    <div class="container">
        <div class="row">
            <div class="col">
                <span id='breadcrumbs'>
                    <a href="{% url 'homepage' %}">Home</a>
                    / 
                    <a href="{% url 'venue_list' %}?zip_code={{ venue.zip_code }}">Venue List</a>
                    /
                    <a href="{% url 'venue_detail' venue_pk=venue.pk %}">{{ venue.name }}</a>
                </span>
            </div>
        </div>
    </div>
    <hr class="mt-0 mb-4">

    <div class="container">
        <div class="row">
            <!-- venue details -->
            <div class="col">
                <div class="venue_list">
                    <h3 style="margin-bottom: 0pt">{{ venue.name }}</h3>
                    <p style="margin-top: 0pt"><i>{{ venue.category }}</i></p>
                    <div class="venue_text">
                        <p>{{ venue.address }}</p>
                        <p>{{ venue.city }}, {{ venue.state }} {{ venue.zip_code }}</p>
                    </div>
                </div>
            </div>
            <!-- venue image -->
            <!-- <img class="venue_images" src="{{ venue.image }}" alt="{{ venue.name }}"> -->
        </div>
    </div>
    <br>

    <!-- form to review restroom -->
    <div class="container">
        <h4>Leave a review</h4>
        <form method="POST" action="{% url 'venue_detail' venue_pk=venue.pk %}">
            {% csrf_token %}

            {% for field in restroom_form %}
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label><br>
                            {{ field|add_class:'form-control' }}
                        </div>
                    </div>
                </div>
            {% endfor %}
            <input type="submit" value="Submit">
        </form>
    </div>

    <!-- if there are any reviews, list them here -->
    <div class="container">
        <h3>Reviews</h3>

        {% if reviews %}
            {% for review in reviews %}
                <div class="venue_list">
                    <h4 style="display: inline-block;"><a href="{% url 'review_detail' review_pk=review.pk %}">{{ review.title }}</a></h4>
                    by {{ review.user }}
                    <div class="review_text">
                        {{ review.rating }}\5&emsp;<i>{{ review.comment }}</i>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No restroom reviews currently available.</p>
        {% endif %}
    </div>

{% endblock %}

restroom_rater/templates/restroom_rater/venue_list.html
{% extends 'restroom_rater/base.html' %}
{% block content %}

    <!-- breadcrumbs -->
    <div class="container">
        <div class="row">
            <div class="col">
                <span id='breadcrumbs'>
                    <a href="{% url 'homepage' %}">Home</a>
                    / 
                    <a href="{% url 'venue_list' %}?zip_code={{ search_location }}">Venue List</a>
                </span>
            </div>
        </div>
    </div>
    <hr class="mt-0 mb-4">

    <!-- if any venues are returned, list them here -->
    <div class="container">
        <div class="row">
            <div class="col">
                {% for venue in venues %}
                    <div class="venue_list">
                        <h3 style="margin-bottom: 0pt"><a href="{% url 'venue_detail' venue_pk=venue.pk %}">{{ venue.name }}</a></h3>
                        <p style="margin-top: 0pt"><i>{{ venue.category }}</i></p>
                        <div class="venue_text">
                            <p>{{ venue.address }}</p>
                            <p>{{ venue.city }}, {{ venue.state }} {{ venue.zip_code }}</p>
                        </div>
                        <br>
                    </div>
                {% empty %}
                    <b><p class="center">There are no venues!</p></b>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}